### ISSUE TITLE
Phone-context missing when fetching live blocking info

### ISSUE THREAD

**Issue by dawnightillight** [apple/live-caller-id-lookup-example#18] opened 2024-07-24 06:38 UTC
Hi,

We found that the phone numbers used to fetch block / identity info have a little bit difference. The console log shows:

when fetching blocking info - 
<img width="960" alt="image" src="https://github.com/user-attachments/assets/65d671da-7ef5-4d8a-8e4a-759e1e31aee3">

when fetching identity info - 
<img width="670" alt="image" src="https://github.com/user-attachments/assets/9543140c-814f-4d96-af43-51e399584cdd">

The `phone-context` '+86' obviously missing in first number. Which results in that if we want to provide both blocking and identity info, there needs to be two identities in database like:
<img width="298" alt="image" src="https://github.com/user-attachments/assets/19e87f9e-386c-4d19-8686-c45f2515918a">

Our extension demo was ran on iOS 18 beta3. It this a bug to be fixed in beta4 or laster version?

**Comment by karulont** [comment] 2024-07-24 15:20
Thank you for reporting, we are looking into it.

**Comment by karulont** [comment] 2024-07-25 01:05
@dawnightillight 
Could you also use feedback assistant to submit a bug report with logs / sysdiagnose after reproducing the issue? This would help the team to narrow down the root cause more quickly.

**Comment by dawnightillight** [comment] 2024-07-25 02:49
okay

**Comment by dawnightillight** [comment] 2024-07-25 07:06
@karulont 
Done, the feedback id is FB14480423.

**Comment by karulont** [comment] 2024-07-30 16:25
The fix for this will land in iOS 18 beta 5 or later.

I am keeping this issue open until the iOS release with the fix has been made public.

**Comment by karulont** [comment] 2024-08-20 23:54
This should be fixed in iOS 18 beta 5.

**Closed by karulont** 2024-08-20 23:54 UTC
